title: Automations
id: automations
path: automations
icon: mdi:home-variant
visible:
  - user: 2e93f54c62e549c8aeperson2748de6bed9d
cards:
- type: entities
  title: Room status
  show_header_toggle: false
  entities:
  - automation.living_room_occupied
  - automation.living_room_not_occupied
  - type: divider
  - automation.living_room_arrival
  - automation.living_room_away
  - automation.living_room_bedtime
  - automation.living_room_day_on
  - automation.living_room_dim
  - automation.living_room_dim_off
  - automation.living_room_night_on
  - automation.living_room_off
- type: entities
  title: Automations for the living room lights
  show_header_toggle: false
  entities:
  - automation.living_room_lights_bedtime
  - automation.living_room_lights_day_on
  - automation.living_room_lights_dim_on
  - automation.living_room_lights_night_on
  - automation.living_room_lights_off
  - type: divider
  - automation.tv_light_on
  - automation.living_room_dark_motion
  - automation.living_room_dark_no_motion
  - type: divider
  - automation.living_room_table_light_unavailable_on
  - automation.living_room_table_light_unavailable_off
- type: entities
  title: Living room media automations
  show_header_toggle: false
  entities:
  - automation.all_away_media_off
  - automation.tv_on_sonos_off
  - automation.sonos_on_tv_mute
  - automation.sonos_off_tv_unmute
- type: entities
  title: Remote automations
  show_header_toggle: false
  entities:
  - automation.dimmer
  - automation.dimmer_on
  - automation.dimmer_off
  - automation.dimmer_on_while_away
  - automation.dimmer_off_while_off
  - automation.dimmer_up_while_on
  - automation.dimmer_down_while_on
- type: entities
  title: House
  show_header_toggle: false
  entities:
  - automation.house_mode_auto
  - automation.house_mode_away
  - automation.house_mode_bedtime
  - automation.house_mode_holiday
- type: entities
  title: Hall
  show_header_toggle: false
  entities:
  - automation.hall_lights_to_away
  - automation.hall_lights_to_bedtime
  - automation.hall_lights_to_dim
  - automation.hall_lights_to_night_on
  - automation.hall_lights_to_off
  - type: divider
  - automation.hall_mode_away
  - automation.hall_mode_bedtime
  - automation.hall_mode_dim
  - automation.hall_mode_night_on
  - automation.hall_mode_off
  - type: divider
  - automation.hall_lights_unavailable_off
- type: entities
  title: Vestibule
  show_header_toggle: false
  entities:
  - automation.vestibule_lights_to_away
  - automation.vestibule_lights_to_bedtime
  - automation.vestibule_lights_to_off
  - automation.vestibule_lights_to_on
  - automation.vestibule_lights_to_night_on
  - type: divider
  - automation.vestibule_mode_away
  - automation.vestibule_mode_bedtime
  - automation.vestibule_mode_off
  - automation.vestibule_mode_on
  - automation.vestibule_mode_night_on
- type: entities
  title: Family room
  show_header_toggle: false
  entities:
  - automation.family_room_occupied
  - automation.family_room_not_occupied
  - type: divider
  - automation.family_room_mode_away
  - automation.family_room_mode_bedtime
  - automation.family_room_mode_off
  - automation.family_room_mode_on
  - type: divider
  - automation.family_room_lights_to_away
  - automation.family_room_lights_to_bedtime
  - automation.family_room_lights_to_off
  - automation.family_room_lights_to_on
- type: entities
  title: Front of the house
  show_header_toggle: false
  entities:
  - automation.number_on_at_sunset
  - automation.number_on_in_the_morning
  - automation.number_sign_off
  - automation.person2_up_early
  - automation.returned_home
  - automation.front_door_open
  - automation.front_door_closed
  - automation.garage_door_open
  - automation.garage_door_closed
  - automation.garage_open_nobody_home
  - automation.person2_away_garage_open
  - automation.probably_leaving
- type: entities
  title: Garden
  show_header_toggle: false
  entities:
  - automation.utility_door_open_after_sunset_closed
  - automation.utility_door_open_after_sunset_turn_on
  - automation.utility_door_open_after_sunset_turn_off
  - automation.nighttime_garden_off
  - automation.garden_lights_left_on
  - automation.utility_door_left_open
  - binary_sensor.garden_lights_left_on
- type: entities
  title: Automations for the office
  show_header_toggle: false
  entities:
  - automation.play_music_in_the_office
  - automation.pause_music_in_the_office
  - automation.resume_music_in_the_office
  - type: divider
  - automation.office_occupied
  - automation.office_not_occupied
  - automation.office_button_pushed
